'use client'
// app/study-plan/page.js
import { useState } from 'react'
import { useAuth } from '../../context/AuthContext'
import AppLayout from '../../components/layout/AppLayout'
import { generateStudyPlan } from '../../lib/gemini'
import { Sparkles, Clock, ChevronDown, ChevronUp, BookOpen } from 'lucide-react'
import toast from 'react-hot-toast'

export default function StudyPlanPage() {
  const [form, setForm] = useState({ subject: '', examDate: '', hoursPerDay: 2, level: 'beginner' })
  const [plan, setPlan] = useState(null)
  const [loading, setLoading] = useState(false)
  const [expanded, setExpanded] = useState(null)
  const set = k => e => setForm(f => ({ ...f, [k]: e.target.value }))

  async function generate() {
    if (!form.subject || !form.examDate) return toast.error('Fill in subject and exam date')
    setLoading(true)
    try {
      const result = await generateStudyPlan(form.subject, form.examDate, form.hoursPerDay, form.level)
      setPlan(result)
      toast.success('Study plan generated!')
    } catch { toast.error('Generation failed. Check your Gemini API key.') }
    finally { setLoading(false) }
  }

  return (
    <AppLayout>
      <div style={s.page}>
        <div style={s.header}>
          <h1 style={s.title}>AI Study Planner</h1>
          <p style={s.sub}>Get a personalized study plan generated by Nova</p>
        </div>

        <div style={s.formCard} className="glass glow-border">
          <h3 style={s.formTitle}><Sparkles size={17} color="var(--indigo-bright)" /> Generate Your Plan</h3>
          <div style={s.grid}>
            <div style={s.field}><label style={s.label}>Subject / Course *</label><input style={s.input} value={form.subject} onChange={set('subject')} placeholder="e.g. Calculus, Python, History" /></div>
            <div style={s.field}><label style={s.label}>Exam / Deadline Date *</label><input style={s.input} type="date" value={form.examDate} onChange={set('examDate')} /></div>
            <div style={s.field}><label style={s.label}>Hours per day</label>
              <select style={s.input} value={form.hoursPerDay} onChange={set('hoursPerDay')}>
                {[1, 1.5, 2, 3, 4, 5, 6].map(h => <option key={h} value={h}>{h}h / day</option>)}
              </select>
            </div>
            <div style={s.field}><label style={s.label}>Your current level</label>
              <select style={s.input} value={form.level} onChange={set('level')}>
                <option value="beginner">🌱 Beginner</option>
                <option value="intermediate">📚 Intermediate</option>
                <option value="advanced">🚀 Advanced</option>
              </select>
            </div>
          </div>
          <button style={s.genBtn} onClick={generate} disabled={loading}>
            <Sparkles size={16} /> {loading ? 'Nova is thinking…' : 'Generate Study Plan'}
          </button>
        </div>

        {plan && (
          <div style={s.plan}>
            <div style={s.planHeader} className="glass glow-border">
              <h2 style={s.planTitle} className="gradient-text">{plan.title}</h2>
              <p style={s.planSub}>{plan.totalDays} day plan · {form.hoursPerDay}h/day</p>
            </div>

            {plan.keyTopics?.length > 0 && (
              <div style={s.section} className="glass">
                <h3 style={s.sectionTitle}>Key Topics</h3>
                <div style={s.chips}>{plan.keyTopics.map((t, i) => <span key={i} style={s.topicChip}>{t}</span>)}</div>
              </div>
            )}

            {plan.resources?.length > 0 && (
              <div style={s.section} className="glass">
                <h3 style={s.sectionTitle}>Resources</h3>
                {plan.resources.map((r, i) => <div key={i} style={s.resItem}><BookOpen size={13} color="var(--indigo-bright)" /><span>{r}</span></div>)}
              </div>
            )}

            <h3 style={{ ...s.sectionTitle, margin: '0 0 0.75rem' }}>Day-by-Day Schedule</h3>
            <div style={s.dayList}>
              {plan.dailyPlans?.map((day, i) => (
                <div key={i} style={s.dayCard} className="glass">
                  <div style={s.dayHeader} onClick={() => setExpanded(expanded === i ? null : i)}>
                    <span style={s.dayNum}>Day {day.day}</span>
                    <span style={s.dayFocus}>{day.focus}</span>
                    <span style={s.dayHours}><Clock size={12} /> {day.hours}h</span>
                    {expanded === i ? <ChevronUp size={15} color="var(--text-muted)" /> : <ChevronDown size={15} color="var(--text-muted)" />}
                  </div>
                  {expanded === i && (
                    <div style={s.dayContent}>
                      {day.tasks?.map((t, j) => <div key={j} style={s.taskItem}><div style={s.taskDot} />{t}</div>)}
                      {day.tips && <div style={s.tipBox}>💡 <em>{day.tips}</em></div>}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </AppLayout>
  )
}

const s = {
  page: { padding: '2rem', maxWidth: '780px', margin: '0 auto' },
  header: { marginBottom: '1.5rem' },
  title: { fontSize: '1.8rem', fontWeight: 900, marginBottom: '4px' },
  sub: { color: 'var(--text-muted)', fontSize: '0.875rem' },
  formCard: { borderRadius: '20px', padding: '1.75rem', marginBottom: '2rem' },
  formTitle: { display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.95rem', fontWeight: 800, marginBottom: '1.25rem' },
  grid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', marginBottom: '1.25rem' },
  field: { display: 'flex', flexDirection: 'column', gap: '5px' },
  label: { fontSize: '0.78rem', fontWeight: 600, color: 'var(--text-muted)' },
  input: { padding: '0.7rem 1rem', background: 'rgba(99,102,241,0.06)', border: '1px solid var(--border2)', borderRadius: '10px', color: 'var(--text)', fontSize: '0.875rem', outline: 'none' },
  genBtn: { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px', width: '100%', padding: '0.875rem', background: 'var(--grad-1)', border: 'none', borderRadius: '12px', color: '#fff', fontSize: '0.95rem', fontWeight: 700, cursor: 'pointer', boxShadow: '0 0 24px rgba(99,102,241,0.3)' },
  plan: { display: 'flex', flexDirection: 'column', gap: '1rem' },
  planHeader: { padding: '1.25rem', borderRadius: '16px' },
  planTitle: { fontSize: '1.25rem', fontWeight: 900, marginBottom: '4px' },
  planSub: { color: 'var(--text-muted)', fontSize: '0.85rem' },
  section: { borderRadius: '14px', padding: '1.25rem' },
  sectionTitle: { fontSize: '0.875rem', fontWeight: 800, marginBottom: '0.75rem', color: 'var(--text)' },
  chips: { display: 'flex', flexWrap: 'wrap', gap: '0.5rem' },
  topicChip: { padding: '4px 12px', background: 'rgba(99,102,241,0.12)', border: '1px solid rgba(99,102,241,0.2)', borderRadius: '999px', color: 'var(--indigo-bright)', fontSize: '0.78rem', fontWeight: 600 },
  resItem: { display: 'flex', alignItems: 'center', gap: '8px', color: 'var(--text-muted)', fontSize: '0.85rem', marginBottom: '5px' },
  dayList: { display: 'flex', flexDirection: 'column', gap: '0.5rem' },
  dayCard: { borderRadius: '12px', overflow: 'hidden' },
  dayHeader: { display: 'flex', alignItems: 'center', gap: '10px', padding: '0.875rem 1rem', cursor: 'pointer' },
  dayNum: { background: 'rgba(99,102,241,0.15)', color: 'var(--indigo-bright)', padding: '3px 10px', borderRadius: '999px', fontSize: '0.75rem', fontWeight: 700, flexShrink: 0 },
  dayFocus: { flex: 1, fontSize: '0.875rem', fontWeight: 700, color: 'var(--text)' },
  dayHours: { display: 'flex', alignItems: 'center', gap: '4px', color: 'var(--text-muted)', fontSize: '0.78rem' },
  dayContent: { padding: '0 1rem 1rem', borderTop: '1px solid var(--border)' },
  taskItem: { display: 'flex', alignItems: 'flex-start', gap: '8px', color: 'var(--text)', fontSize: '0.85rem', padding: '5px 0' },
  taskDot: { width: '5px', height: '5px', borderRadius: '50%', background: 'var(--indigo-bright)', marginTop: '7px', flexShrink: 0 },
  tipBox: { background: 'rgba(34,211,238,0.06)', border: '1px solid rgba(34,211,238,0.15)', borderRadius: '8px', padding: '9px 12px', color: 'var(--text-muted)', fontSize: '0.8rem', marginTop: '0.75rem' },
}
